# Generated by Django 5.2.10 on 2026-03-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cliente_cpf_alter_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estoque',
            field=models.IntegerField(default=0),
        ),
    ]
